[[module.imports]]
  path = "github.com/philipbelesky/inter-ui"

  [[module.imports.mounts]]
    source = "Inter (web)/Inter-roman.var.woff2"
    target = "static/fonts/Inter/Inter-roman.var.woff2"
  [[module.imports.mounts]]
    source = "Inter (web)/Inter-italic.var.woff2"
    target = "static/fonts/Inter/Inter-italic.var.woff2"